NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
ACCOUNTS=[
"GC4RZG4AA57JRUBALFCTYGSDUM4CCXS6OCIP7MY3W5HUWXEOIL3PEX7B",
"GBKIXUFPW3XMMOMUPBPEZVNWVSVREZ5YFXKBXP7MC5B2W5RJMIYJU3IR"
]
VERSION="1.0.0"

[DOCUMENTATION]
ORG_NAME="Runciter Associates"
ORG_DBA="Runciter"
ORG_URL="https://ubik.port0.org/"
ORG_LOGO="https://ubik.port0.org/logo.png"
ORG_PHYSICAL_ADDRESS="Luna"

[[PRINCIPALS]]
name="Joe Chip"
email="hellojoechip@gmail.com"

[[CURRENCIES]]
code="UBIK"
name="Ubik"
desc="A research project – and a tribute to one of the best books ever written."
issuer="GC4RZG4AA57JRUBALFCTYGSDUM4CCXS6OCIP7MY3W5HUWXEOIL3PEX7B"
image="https://ubik.port0.org/ubik.png"
display_decimals=2
is_asset_anchored=false
