NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
ACCOUNTS=[
"GC4RZG4AA57JRUBALFCTYGSDUM4CCXS6OCIP7MY3W5HUWXEOIL3PEX7B",
"GBKIXUFPW3XMMOMUPBPEZVNWVSVREZ5YFXKBXP7MC5B2W5RJMIYJU3IR"
]
VERSION="1.0.0"

[DOCUMENTATION]
ORG_NAME="Runciter Associates"
ORG_DBA="Joe Chip"
ORG_URL="https://ubik.us.to"
ORG_LOGO="https://ubik.us.to/logo.png"
ORG_PHYSICAL_ADDRESS="Luna"

[[PRINCIPALS]]
name="Joe Chip"
email="hellojoechip@gmail.com"

[[CURRENCIES]]
code="UBIK"
issuer="GC4RZG4AA57JRUBALFCTYGSDUM4CCXS6OCIP7MY3W5HUWXEOIL3PEX7B"
display_decimals=2
is_asset_anchored=false
